Add routines that don't require openssl for SAS key generation.
avnet-iotconnect/iotc-generic-c-sdk pull request #24
Opened 2023-07-04 17:06 UTC by nmatthews-witekio

Use an error/warn/debug mechanism (needs iotc-c-lib modification) rather than using printf, etc. Fix crashes when cJSON fails (due to issue with floating-point output).

2023-07-04 17:07 UTC, nmatthews-witekio commented
This is a checkpoint / WIP -- need to double-check is ok on "normal" platforms

2023-07-14 17:27 UTC, nik-markovic requested changes

2023-08-23 11:28 UTC, closed without merging

2023-08-23 11:28 UTC, nmatthews-witekio commented
Changes are rolled up in https://github.com/avnet-iotconnect/iotc-c-lib/pull/20

2023-08-23 11:32 UTC, nmatthews-witekio commented on iotc-generic-c-sdk/src/iotconnect.c
> +    IOTC_ERROR("%s", message);
Can't tell from printf whether it's an error / log / debug / warning -- so use a couple of minor macros to make it explicit.
Makes it easier to hide debug/logging -- just don't implement macro.
Can add function name, extra timing information, thread id, etc. if required without having to change all printf() formatting.

Also makes it a lot easier to port to a system that doesn't have printf.